### PR TITLE
ionic-v7 - angular 16.x with standalone component migration

### PR DESCRIPTION
**Pull request by vc-rakesh**
ionic-v7 - angular 16.x with standalone component migration

### CODE REVIEW

**Comment by eakoriakin** [comment]
Hi @vc-rakesh nice work! Unfortunately, I don't have time to maintain the component myself at the moment.
However, I'd be happy to grant you permissions so you could merge the PR yourself and then build and publish the component to `npm`. What do you think?

**Comment by vc-rakesh** [comment]
Hey @eakoriakin 
I think it's a good idea.

**Comment by eakoriakin** [comment]
@vc-rakesh great! I've sent you an invite for the repository. Tell me your NPM username and I'll add your there as well.

**Comment by vc-rakesh** [comment]
Hey @eakoriakin its **vc-rakesh**

Thanks

**Comment by eakoriakin** [comment]
@vc-rakesh done, gave you npm access as well. Good luck :)

**Pull request merged**
